import type { Song } from "@/lib/types";

export const DEMO_SONGS: Song[] = [
  {
    id: "demo-last-call",
    title: "Last Call",
    subtitle: "Don't clean it up",
    bpm: 94,
    key: "A minor",
    genre: "trap",
    explicit: true,
    vocalMode: "rap",
    mood: "Neon parking lot, last round, no morals left",
    prompt: "Late-night trap about last call and a bad idea",
    mode: "solo",
    vocalistA: "diesel",
    vocalistB: null,
    createdAt: "2026-01-01T00:00:00.000Z",
    isDemo: true,
    sections: [
      {
        id: "intro",
        label: "Intro",
        kind: "intro",
        bars: 4,
        vocalistId: "diesel",
        lyrics: "",
        chords: ["Am", "Am", "F", "E"],
      },
      {
        id: "verse1",
        label: "Verse",
        kind: "verse",
        bars: 8,
        vocalistId: "diesel",
        lyrics: [
          "Last call, lights low, I don't wanna go home",
          "She said pull me closer, we can be alone",
          "Backseat gospel, I don't need a throne",
          "If the night is dirty, girl we making it known",
          "Ice in the cup, sin on my tongue",
          "I been gone too long, now I'm coming undone",
          "Don't ask me who I was when the sun was up",
          "After hours I don't give a fuck",
        ].join("\n"),
        chords: ["Am", "F", "C", "E"],
      },
      {
        id: "chorus",
        label: "Chorus",
        kind: "chorus",
        bars: 8,
        vocalistId: "diesel",
        lyrics: [
          "Don't clean it up",
          "Don't clean it up",
          "We only get this dark once",
          "Don't clean it up",
          "Put your mouth on the bruise",
          "Let the bass get rude",
          "If the morning gonna judge us",
          "Let it wait in the booth",
        ].join("\n"),
        chords: ["Am", "G", "F", "E"],
      },
    ],
  },
  {
    id: "demo-two-shadows",
    title: "Two Shadows",
    subtitle: "One bed, two mouths",
    bpm: 86,
    key: "D minor",
    genre: "rnb",
    explicit: true,
    vocalMode: "hybrid",
    mood: "Motel argument that keeps turning back into sex",
    prompt: "R&B and rock mashup, motel at 3am",
    mode: "mashup",
    vocalistA: "sal",
    vocalistB: "leo",
    createdAt: "2026-01-01T00:00:00.000Z",
    isDemo: true,
    sections: [
      {
        id: "intro",
        label: "Intro",
        kind: "intro",
        bars: 4,
        vocalistId: "sal",
        lyrics: "",
        chords: ["Dm", "Bb", "F", "C"],
      },
      {
        id: "verse1",
        label: "Verse · Leo",
        kind: "verse",
        bars: 8,
        vocalistId: "leo",
        lyrics: [
          "You said never again with your lipstick still on",
          "Now you kicking the door like the fight ain't gone",
          "I can taste the whiskey and the almost-divorce",
          "Keep your clothes on the lamp, keep your nails in my back",
          "If we talking about leaving, girl we already packed",
          "Then you kiss like a dare and the argument cracks",
          "Two shadows on the wall doing what we said we wouldn't",
          "If this is a mistake, then I'm making it public",
        ].join("\n"),
        chords: ["Dm", "Bb", "F", "C"],
      },
      {
        id: "chorus",
        label: "Chorus · Sal",
        kind: "chorus",
        bars: 8,
        vocalistId: "sal",
        lyrics: [
          "Come here, we can hate it in the morning",
          "Right now put your teeth on my shoulder",
          "Two shadows, one bed, no warning",
          "If you leave, leave it hotter",
          "Come here, we can hate it in the morning",
          "Say my name like you mean the damage",
          "Two shadows, one bed, no warning",
          "Baby don't you dare go average",
        ].join("\n"),
        chords: ["Gm", "Bb", "F", "C"],
      },
    ],
  },
];
